---
- name: Get RackHD from source
  git: repo=https://github.com/rackhd/rackhd
       dest="/home/vagrant/src"
       accept_hostkey=true
       version="{{ branch | default('master') }}"

- name: Update git repos with latest
  shell: git fetch --all --prune
  args:
    chdir: "/home/vagrant/src/{{ item }}"
  with_items:
    - on-core
    - on-tasks
    - on-http
    - on-tftp
    - on-dhcp-proxy
    - on-taskgraph
    - on-syslog

- name: Reset to the branch specified
  shell: git reset --hard {{ branch }}
  when: branch is defined
  args:
    chdir: "/home/vagrant/src/{{ item }}"
  with_items:
    - on-core
    - on-tasks
    - on-http
    - on-tftp
    - on-dhcp-proxy
    - on-taskgraph
    - on-syslog

- name: Npm install Repos
  npm: path="/home/vagrant/src/{{ item }}"
       production=yes
  with_items:
    - on-syslog
    - on-tftp
    - on-dhcp-proxy
    - on-taskgraph
    - on-http

- name: Make common static directory
  file: path="/home/vagrant/src/on-http/static/http/common" state=directory

- name: Npm install apidoc
  shell: "npm install apidoc"
  args:
    chdir: "/home/vagrant/src/on-http"

- name: Render API docs for local reference
  shell: "npm run apidoc"
  args:
    chdir: "/home/vagrant/src/on-http"

- name: set HTTP static directory for RackHD
  set_fact: http_static_directory="/home/vagrant/src/on-http/static/http"

- name: set TFTP static directory for RackHD
  set_fact: tftp_static_directory="/home/vagrant/src/on-tftp/static/tftp"
