---
- name: Install foreman
  shell: npm install -g foreman
  sudo: yes

- name: Copy foreman .env file to home directory
  copy: src=.env dest="/home/vagrant/"
  sudo: yes

- name: Copy foreman Procfile to home directory
  copy: src=Procfile dest="/home/vagrant/"
  sudo: yes
