---
- name: Install isc-dhcp-server
  apt: pkg={{ item }} state=installed
  with_items:
    - isc-dhcp-server
  sudo: yes

- name: Copy isc-dhcp-server file to guest
  copy: src=isc-dhcp-server dest=/etc/default/isc-dhcp-server
  sudo: yes

- name: Copy dhcpd.conf file to guest
  copy: src=dhcpd.conf dest=/etc/dhcp/dhcpd.conf
  sudo: yes
